language: java
install: true
matrix:
  include:
  - jdk: oraclejdk8
script: mvn clean verify install -DskipTests=false -Dmaven.javadoc.skip=true -B -V
env:
  global:
    secure: XpArBRq0bKup5UYe7cOLqBSK4iXkG6p5YMNNBVIWjxHXiRuBxdFu4eXCu03scIzoe/GyXD65grSsZevAekK0lJZAd0/T62n0hfuWxw/NWHD+lbJRuGxNbwcqTvihLs8Np4Cicj7S+aWMZLdUc7eTrvx/nrs13PGUvHwn0eBo/GPrGYD3Jh/zaDG9c4w920tkq8u9telyl5sTF4ElrY2aneQbqRxs7zLLnDtLc+wdvNtfeAdGVD74mRzUSsWP+FFGea4nqA1A7qaXKSvIpdo3ympxZNCTBu3jMAGPSDk7CRnJOZYlLcNqqpeWdsCvPRst4Y57dPhstzv5KicDMuicZHUJddeXCFqtxYxvhj1rvsAud8L79KYDEC+Dux4qvW2uu5B79JwROTJlHdcC7FckikOHcp8KgHXJuwQbtboPemZ22dZvgK+TJKcp/tvvgGScZkJ9jPBwhRjFllblz6X2nRx8UNcHtrIwIP5PnYI1t95yGYlImVuzdv6uWW8uQxCvePCTBPHsBLnRvsT03MBAnbk1I9GiqHZntVWnxQcbcSXzl8gTpgEhSs/PiOimRyaP/WG7+rEOPXZ/n/VdfwvoN4a4p/KVb2mo3WbiLNxtrHYjJoN3+4V/3/nRRI4c6CvS9yHnMqQQ99ZAlKSnMVUpW30y3y6WL7I8tTw3aNr5+38=
after_success:
- mvn org.eluder.coveralls:coveralls-maven-plugin:report
- git config --global user.email "builds@travis-ci.com"
- git config --global user.name "Travis CI"
- export GIT_TAG=$TRAVIS_BRANCH-v1.0.$TRAVIS_BUILD_NUMBER
- git tag $GIT_TAG -a -m "Generated tag from TravisCI for build $TRAVIS_BUILD_NUMBER"
- git push https://${GH_TOKEN}:x-oauth-basic@github.com/mitoskalandiel/HostsEdit.git --tags
deploy:
  provider: releases
  api_key:
    secure: FX3x9+hM23Uc4qdrgT3a+m8vo+ZQkNI78PJ141SXWUZZzViOkbkwjyILt/0CLSAUT4yk7r5HMMFur9VVDZZwThr4ukKu9j8+qIAt5t8qpG/e6dZp7A7Rt9k4OlUdEapISCsP1wSspJ7aDi1zPkf0DF88qirlIEJmWPf4PW80PzX7RSZoxD7MoG8sGPt5eYeBstCz46DjXKdX3YwHsKIhdZOTPwSblLMgT7QF7iFdIbxXx7f6wggPn+uFjSiKqUx+aHa2Rw/7RZDOH3nMztj+SLBaqVr2QVbpkW9Z2yRNb86Rv1AZMnAu/0oIcgbeMiHeJDtaPQJzTFvJV0OXO/X486gXHDfzBr59infC/54VOt6siJpKu9dYTBP0TvCTtyIaD69QjStsBQ32FAJkgx7kqzL1G3P2tVTHcYESX4P78TNMn00BxsXapRS+d+9T61ivdUtnSm9bRWOjOPIyZ+m1IPcXDNcL4f9NiLx1K67FUb8PY91+DYO7eZC8owJxpNSLGC5h8xpz5Ms34fYYr2EdnFPhn2z09pemcV28sjU8+9hwflsJ0hjaFnMxH4/S0Z1dHbpU5pBxL9O2f7DJcU6P2yfBUIt53L3pkmnqAjOrufqaN1IEoHENd3hFjSwp4muq6CUFCPJ3aj1drJarkwrl2vbES4Fni/w7kYWGBtwyvxI=
  file:
  - target/HostsEdit-v1.0.jar
  on:
    tags: false
    all_branches: true
branches:
  except:
  - "/^*-v[0-9]/"
addons:
  code_climate:
    repo_token: 96557def378bdcf81aac3dd6fb1e8fb9a09b9e7990dbda41515e7cf37dec9789
cache:
  directories:
  - "$HOME/.m2"
  - "$HOME/.rvm"
