language: csharp
solution: MyHostsEdit.sln
sudo: required
install:
  - nuget restore MyHostsEdit.sln
  - nuget install NUnit.Runners -Version 3.5.0 -OutputDirectory nunit-runner
script:
  - xbuild /p:Configuration=Release MyHostsEdit.sln
  - mono ./nunit-runner/NUnit.Runners.3.5.0/tools/nunit-console.exe ./JokerApiTests/bin/Release/JokerApiTests.dll