language: java
install: true
matrix:
  include:
  - jdk: oraclejdk8
before_install:
- openssl aes-256-cbc -K $encrypted_8b1807510560_key -iv $encrypted_8b1807510560_iv -in .coveralls.yml.enc -out .coveralls.yml -d
script: mvn clean verify install -DskipTests=false -Dmaven.javadoc.skip=true -B -V
env:
  global:
    secure: ga+p8gfqtcZDS8Atb0mYTEveAo9ssAgXzv5wNrsnUGrZVknB/Dqt0KIFOKvixdxOxPSbosYGqdszyaQ/638fk4RnBirtrEABPwFuSQAbmFSZw37jmstUDsBWjrSBojTpQ3H9qTHPEoIAVsVH7PlfSHPID1tXw5Dyxw/bvVL7uXkpPDQuWvlo8dd5gAm6zLu3DzpqPgC14p/sjsLNAwXB4fWM9AXdBb+nkkyqnWNSUN914Ko6I6g5psYyR2zEbuIIeblfaSQByuBdjT6TaCAhLlssNQJWDJEB0JDfCo25ssVqHdYSQK6444DtOppI2Ogn/IvCXTrFjFWciGnKCXHvVL6RlVU1v/mIPkSzjcP7JVVsKNWMdXbjLt507bBI3N9EM5yeHrvlBjP3LCYmEUiUOfCgetA0gSLQ62a/aIgz5bIVWfur601X5lhuo/qXhbdMxEf4+L9LtnNruRAUpJzZMOLgaiS+VRql7Oh4MPIIn/HV0FlrubP1+DmgzO2fcvIgNStuMbRgsd+DBDA3FX4UBhmIZMndAp+RZ2AFXt7LuORZ5USd7IQfhRImgjuFJsn6xD3lt3kNkosFt/onHB3HDwkJACI88JyHS3ItxuY74t4Qhu4lghfVhujFTmSlCLfAITpiz+VOTncnXzSe6UX+YF5HXe9EcI1rv30cZPM6PUs=
after_success:
- mvn org.eluder.coveralls:coveralls-maven-plugin:report org.jacoco:jacoco-maven-plugin:prepare-agent sonar:sonar
- git config --global user.email "builds@travis-ci.com"
- git config --global user.name "Travis CI"
- export GIT_TAG=$TRAVIS_BRANCH-v1.0.$TRAVIS_BUILD_NUMBER
- git tag $GIT_TAG -a -m "Generated tag from TravisCI for build $TRAVIS_BUILD_NUMBER"
- git push https://${GH_TOKEN}:x-oauth-basic@github.com/mitoskalandiel/HostsEdit.git --tags
deploy:
  provider: releases
  skip_cleanup: true
  api_key:
    secure: FX3x9+hM23Uc4qdrgT3a+m8vo+ZQkNI78PJ141SXWUZZzViOkbkwjyILt/0CLSAUT4yk7r5HMMFur9VVDZZwThr4ukKu9j8+qIAt5t8qpG/e6dZp7A7Rt9k4OlUdEapISCsP1wSspJ7aDi1zPkf0DF88qirlIEJmWPf4PW80PzX7RSZoxD7MoG8sGPt5eYeBstCz46DjXKdX3YwHsKIhdZOTPwSblLMgT7QF7iFdIbxXx7f6wggPn+uFjSiKqUx+aHa2Rw/7RZDOH3nMztj+SLBaqVr2QVbpkW9Z2yRNb86Rv1AZMnAu/0oIcgbeMiHeJDtaPQJzTFvJV0OXO/X486gXHDfzBr59infC/54VOt6siJpKu9dYTBP0TvCTtyIaD69QjStsBQ32FAJkgx7kqzL1G3P2tVTHcYESX4P78TNMn00BxsXapRS+d+9T61ivdUtnSm9bRWOjOPIyZ+m1IPcXDNcL4f9NiLx1K67FUb8PY91+DYO7eZC8owJxpNSLGC5h8xpz5Ms34fYYr2EdnFPhn2z09pemcV28sjU8+9hwflsJ0hjaFnMxH4/S0Z1dHbpU5pBxL9O2f7DJcU6P2yfBUIt53L3pkmnqAjOrufqaN1IEoHENd3hFjSwp4muq6CUFCPJ3aj1drJarkwrl2vbES4Fni/w7kYWGBtwyvxI=
  file:
  - target/HostsEdit-v1.1-SNAPSHOT.jar
  on:
    tags: false
    all_branches: true
branches:
  except:
  - "/^*-v[0-9]/"
addons:
  srcclr: true
  code_climate:
    repo_token: 96557def378bdcf81aac3dd6fb1e8fb9a09b9e7990dbda41515e7cf37dec9789
  sonarqube:
    token:
      secure: lJ6DRvWNFBS5rw2/2YoTTVJjhsGZxiqDorUCSHsGy8g885RLY4s0H3cre8PWACuk6PqVxIAJ2kQvIYvl66A/dD18xhCc1PPYbcQqGUTA3kpc50ZcdpeNWJABtPpM18bPxcX0Qu3K3VSVJt7Er6Zz9jrLYrHjOwxUe4xRCiaTgoV1U9bp2dk7hDYv4zTAQGg5pU+9YvXzqcN1VVw6wed0Qyj5MSiZzacESAp8Blh4rvE1euPfX3fHRc9I3OrP5rPVOwFUhjr0I5WwbQOIYWx7usVqQr/2vYm3fAdL000VsCVjhSXlwZ6dhdZ8gW4CTFauS90yPri9MNYXBRk1/J+NggZbMZmhSx2t1aLBoN8F9kErqlID19FEBwYxX7SoQvIDHeab0I8rHvv+HzJKTiBMJoqOyg59dWi3FiUwz17tdXkA31CId4dNReglchcqMUmSevsix73U4UypcQFFo3n9IFRSH8kV4CORaevKhYqeTFloFwmHwCHiLcxJHaIb7hFDUtPk2li7sXmo5TJQKrAfcQRW1jqR/Gt/Dck56ZHUFWJzC6H+yAYICzc3A5UEJSWUrUw3v7FKR62/QGjInW59yUkvdD/THGCeyOATWlnLMayE1de46OcqGb+iAcbkyAi79XLEKPf7QGR3jMMnP3saDqYkLvB5GOKV1/tAVNyAn3Q=
    branches:
    - master
    - dev
cache:
  directories:
  - "$HOME/.m2"
  - "$HOME/.rvm"
