language: csharp
solution: MyHostsEdit.sln
sudo: required
install:
  - nuget restore MyHostsEdit.sln
  - nuget install NUnit.Runners -Version 2.6.4 -OutputDirectory testrunner
script:
  - xbuild /p:Configuration=Release MyHostsEdit.sln
  - mono ./testrunner/NUnit.Runners.2.6.4/tools/nunit-console.exe ./JokerApiTests/bin/Release/JokerApiTests.dll